# Generated by Django 4.0.6 on 2022-08-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='Notification',
        ),
    ]
